import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useHideComment, useHideTopic, useReports, useResolveReport, } from '../../lib/communityQueries';
export default function ModerationPage() {
    const [tab, setTab] = useState('open');
    const reports = useReports(tab);
    const resolve = useResolveReport();
    const hideComment = useHideComment();
    const hideTopic = useHideTopic();
    return (_jsxs("section", { children: [_jsxs("header", { style: { display: 'flex', alignItems: 'center', gap: '0.75rem' }, children: [_jsx("h2", { style: { margin: 0 }, children: "Moderation" }), _jsx("nav", { style: { display: 'flex', gap: '0.5rem', marginLeft: '1rem' }, children: ['open', 'resolved'].map((t) => (_jsx("button", { onClick: () => setTab(t), style: {
                                background: tab === t ? 'var(--color-accent)' : '#1f2330',
                                color: 'white',
                            }, children: t === 'open' ? '신고 큐' : '처리됨' }, t))) })] }), reports.isLoading ? _jsx("p", { children: "\uB85C\uB529 \uC911\u2026" }) : null, reports.isError ? (_jsx("p", { style: { color: 'var(--color-fail)' }, children: reports.error.message })) : null, reports.isSuccess ? (_jsxs("table", { style: { width: '100%', borderCollapse: 'collapse', marginTop: '1rem' }, children: [_jsx("thead", { children: _jsxs("tr", { style: { textAlign: 'left', borderBottom: '1px solid #1f2330' }, children: [_jsx("th", { children: "report_id" }), _jsx("th", { children: "\uB300\uC0C1" }), _jsx("th", { children: "\uC0AC\uC720" }), _jsx("th", { children: "\uC81C\uBCF4\uC790" }), _jsx("th", { children: "\uC0C1\uD0DC" }), _jsx("th", { children: "\uC811\uC218 \uC2DC\uAC01" }), _jsx("th", { children: "\uC561\uC158" })] }) }), _jsxs("tbody", { children: [reports.data.map((r) => (_jsxs("tr", { style: { borderBottom: '1px solid #1f2330' }, children: [_jsx("td", { children: _jsx("code", { children: r.report_id.slice(0, 8) }) }), _jsxs("td", { children: [_jsx("span", { className: "badge", children: r.target_type }), _jsx("code", { style: { marginLeft: '0.5rem' }, children: r.target_id.slice(0, 12) })] }), _jsx("td", { children: r.reason }), _jsx("td", { children: _jsx("code", { children: r.reporter_user_id.slice(0, 8) }) }), _jsx("td", { children: _jsx("span", { className: `badge ${r.status === 'open' ? 'badge-warn' : 'badge-pass'}`, children: r.status }) }), _jsx("td", { children: new Date(r.created_at).toLocaleString('ko-KR') }), _jsx("td", { children: r.status === 'open' ? (_jsxs("div", { style: { display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }, children: [_jsx("button", { onClick: () => resolve.mutate({ report_id: r.report_id, action: 'hide_target' }), disabled: resolve.isPending, style: { background: 'var(--color-fail)' }, children: "\uB300\uC0C1 \uC228\uAE40" }), _jsx("button", { onClick: () => resolve.mutate({ report_id: r.report_id, action: 'dismiss' }), disabled: resolve.isPending, style: { background: '#1f2330' }, children: "\uAE30\uAC01" }), r.target_type === 'comment' ? (_jsx("button", { onClick: () => hideComment.mutate(r.target_id), disabled: hideComment.isPending, style: { background: '#1f2330' }, children: "\uB313\uAE00 \uC989\uC2DC \uC228\uAE40" })) : null, r.target_type === 'board_topic' ? (_jsx("button", { onClick: () => hideTopic.mutate(r.target_id), disabled: hideTopic.isPending, style: { background: '#1f2330' }, children: "\uD1A0\uD53D \uC989\uC2DC \uC228\uAE40" })) : null] })) : (_jsx("span", { className: "muted", children: "\uCC98\uB9AC \uC644\uB8CC" })) })] }, r.report_id))), reports.data.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 7, style: { padding: '2rem', textAlign: 'center' }, className: "muted", children: "\uD050\uAC00 \uBE44\uC5B4\uC788\uC2B5\uB2C8\uB2E4." }) })) : null] })] })) : null] }));
}
